# Generated by Django 5.1.5 on 2025-01-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('born_date', models.DateField()),
                ('value', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('value', models.FloatField()),
                ('due_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contracts')),
            ],
        ),
    ]
